/**
 * A/S 접수관리 Mock 데이터
 */

import type {
  ASReceiptData,
  SiteOption,
  TradeOption,
} from '@/src/types/asReceipt';

// 현장 옵션 목업 데이터
export const mockSiteOptions: SiteOption[] = [
  { id: 'SITE_001', name: 'A현장' },
  { id: 'SITE_002', name: 'B현장' },
  { id: 'SITE_003', name: 'C현장' },
  { id: 'SITE_004', name: 'D현장' },
];

// 공종 옵션 목업 데이터
export const mockTradeOptions: TradeOption[] = [
  {
    id: 'TRADE_001',
    name: '전기',
    subTrades: [
      { id: 'SUB_001', name: '스위치' },
      { id: 'SUB_002', name: '콘센트' },
      { id: 'SUB_003', name: '조명' },
      { id: 'SUB_004', name: '배선' },
    ],
  },
  {
    id: 'TRADE_002',
    name: '설비',
    subTrades: [
      { id: 'SUB_005', name: '배관' },
      { id: 'SUB_006', name: '보일러' },
      { id: 'SUB_007', name: '급수' },
      { id: 'SUB_008', name: '급탕' },
    ],
  },
  {
    id: 'TRADE_003',
    name: '창호',
    subTrades: [
      { id: 'SUB_009', name: '현관문' },
      { id: 'SUB_010', name: '발코니' },
      { id: 'SUB_011', name: '창틀' },
      { id: 'SUB_012', name: '유리' },
    ],
  },
  {
    id: 'TRADE_004',
    name: '마감',
    subTrades: [
      { id: 'SUB_013', name: '벽지' },
      { id: 'SUB_014', name: '바닥재' },
      { id: 'SUB_015', name: '타일' },
      { id: 'SUB_016', name: '도배' },
    ],
  },
];

// A/S 접수 목업 데이터
export const mockASReceiptData: ASReceiptData[] = [
  {
    id: 'AS-24001',
    siteName: 'A현장',
    dong: '101',
    ho: '1203',
    trade: '전기',
    subTrade: '스위치',
    defectType: {
      level1: '전기',
      level2: '스위치',
      level3: '거실',
      level4: '지연점등',
    },
    status: 'RECEIVED',
    priority: 'HIGH',
    partner: '한빛전기',
    assignee: '김기사',
    requester: '입주자-홍길동',
    requestedAt: '2025-10-01',
    dueDate: '2025-10-05',
    photos: {
      far: ['/images/as/far1.jpg'],
      near: ['/images/as/near1.jpg'],
    },
    attachments: [
      {
        id: 'ATT_001',
        fileName: '현장사진.pdf',
        fileSize: 2048576,
        fileUrl: '/files/as/photo1.pdf',
        uploadedAt: '2025-10-01T09:00:00',
      },
    ],
    description: '현관 스위치 불빛이 늦게 들어옴',
    comments: 2,
    histories: [
      {
        id: 'HIST_001',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-10-01T09:00:00',
        oldValue: '',
        newValue: 'RECEIVED',
      },
    ],
    approval: {
      isApproved: false,
    },
  },
  {
    id: 'AS-24002',
    siteName: 'B현장',
    dong: '102',
    ho: '805',
    trade: '설비',
    subTrade: '배관',
    defectType: {
      level1: '설비',
      level2: '배관',
      level3: '주방',
      level4: '누수',
    },
    status: 'ASSIGNED',
    priority: 'URGENT',
    partner: '대성설비',
    assignee: '이기사',
    requester: '입주자-김철수',
    requestedAt: '2025-10-02',
    dueDate: '2025-10-04',
    photos: {
      far: ['/images/as/far2.jpg'],
      near: ['/images/as/near2.jpg', '/images/as/near2-1.jpg'],
    },
    attachments: [],
    description: '주방 싱크대 하부 누수 발견',
    comments: 5,
    histories: [
      {
        id: 'HIST_002',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-10-02T10:00:00',
        oldValue: '',
        newValue: 'RECEIVED',
      },
      {
        id: 'HIST_003',
        type: 'ASSIGNMENT',
        title: '담당자 배정',
        description: '이기사님에게 배정되었습니다.',
        createdBy: '관리자-박현장',
        createdAt: '2025-10-02T11:00:00',
        oldValue: '',
        newValue: '이기사',
      },
    ],
    approval: {
      isApproved: false,
    },
  },
  {
    id: 'AS-24003',
    siteName: 'A현장',
    dong: '103',
    ho: '1502',
    trade: '창호',
    subTrade: '현관문',
    defectType: {
      level1: '창호',
      level2: '현관문',
      level3: '도어락',
      level4: '작동불량',
    },
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    partner: '삼성창호',
    assignee: '박기사',
    requester: '입주자-이영희',
    requestedAt: '2025-10-03',
    dueDate: '2025-10-08',
    photos: {
      far: ['/images/as/far3.jpg'],
      near: [],
    },
    attachments: [
      {
        id: 'ATT_002',
        fileName: '도어락_작동영상.mp4',
        fileSize: 10485760,
        fileUrl: '/files/as/video1.mp4',
        uploadedAt: '2025-10-03T14:00:00',
      },
    ],
    description: '현관 도어락이 가끔씩 작동하지 않음',
    comments: 3,
    histories: [
      {
        id: 'HIST_004',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-10-03T14:00:00',
      },
      {
        id: 'HIST_005',
        type: 'ASSIGNMENT',
        title: '담당자 배정',
        description: '박기사님에게 배정되었습니다.',
        createdBy: '관리자-최소장',
        createdAt: '2025-10-03T15:00:00',
      },
      {
        id: 'HIST_006',
        type: 'STATUS_CHANGE',
        title: '처리 시작',
        description: '현장 방문 예정',
        createdBy: '박기사',
        createdAt: '2025-10-04T09:00:00',
        oldValue: 'ASSIGNED',
        newValue: 'IN_PROGRESS',
      },
    ],
    approval: {
      isApproved: false,
    },
  },
  {
    id: 'AS-24004',
    siteName: 'C현장',
    dong: '201',
    ho: '307',
    trade: '마감',
    subTrade: '벽지',
    defectType: {
      level1: '마감',
      level2: '벽지',
      level3: '거실',
      level4: '들뜸',
    },
    status: 'QA',
    priority: 'LOW',
    partner: '명품마감',
    assignee: '정기사',
    requester: '입주자-최민수',
    requestedAt: '2025-09-28',
    dueDate: '2025-10-03',
    photos: {
      far: ['/images/as/far4.jpg'],
      near: ['/images/as/near4.jpg'],
    },
    attachments: [],
    description: '거실 벽지 모서리 부분 들뜸 현상',
    comments: 7,
    histories: [
      {
        id: 'HIST_007',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-09-28T10:00:00',
      },
      {
        id: 'HIST_008',
        type: 'STATUS_CHANGE',
        title: '품질검수 대기',
        description: '처리 완료 후 검수 대기중',
        createdBy: '정기사',
        createdAt: '2025-10-02T16:00:00',
        oldValue: 'IN_PROGRESS',
        newValue: 'QA',
      },
    ],
    approval: {
      isApproved: false,
    },
  },
  {
    id: 'AS-24005',
    siteName: 'B현장',
    dong: '104',
    ho: '609',
    trade: '전기',
    subTrade: '콘센트',
    defectType: {
      level1: '전기',
      level2: '콘센트',
      level3: '주방',
      level4: '작동불량',
    },
    status: 'DONE',
    priority: 'MEDIUM',
    partner: '한빛전기',
    assignee: '김기사',
    requester: '입주자-박지민',
    requestedAt: '2025-09-25',
    dueDate: '2025-09-30',
    completedAt: '2025-09-29',
    photos: {
      far: ['/images/as/far5.jpg'],
      near: ['/images/as/near5.jpg'],
    },
    attachments: [],
    description: '주방 콘센트 전원이 들어오지 않음',
    comments: 4,
    histories: [
      {
        id: 'HIST_009',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-09-25T11:00:00',
      },
      {
        id: 'HIST_010',
        type: 'STATUS_CHANGE',
        title: '처리 완료',
        description: '콘센트 교체 완료',
        createdBy: '김기사',
        createdAt: '2025-09-29T14:00:00',
        oldValue: 'IN_PROGRESS',
        newValue: 'DONE',
      },
    ],
    approval: {
      isApproved: true,
      approvedBy: '관리자-박현장',
      approvedAt: '2025-09-29T15:00:00',
    },
  },
  {
    id: 'AS-24006',
    siteName: 'D현장',
    dong: '105',
    ho: '1104',
    trade: '설비',
    subTrade: '보일러',
    defectType: {
      level1: '설비',
      level2: '보일러',
      level3: '온도조절',
      level4: '오작동',
    },
    status: 'REJECTED',
    priority: 'HIGH',
    partner: '대성설비',
    assignee: '이기사',
    requester: '입주자-강서연',
    requestedAt: '2025-10-04',
    dueDate: '2025-10-08',
    photos: {
      far: ['/images/as/far6.jpg'],
      near: [],
    },
    attachments: [],
    description: '보일러 온도 설정이 제대로 작동하지 않음',
    comments: 6,
    histories: [
      {
        id: 'HIST_011',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-10-04T09:00:00',
      },
      {
        id: 'HIST_012',
        type: 'STATUS_CHANGE',
        title: '반려',
        description: '사용자 조작 미숙으로 인한 오인 신고',
        createdBy: '관리자-최소장',
        createdAt: '2025-10-05T10:00:00',
        oldValue: 'ASSIGNED',
        newValue: 'REJECTED',
      },
    ],
    approval: {
      isApproved: false,
      rejectedReason: '사용자 조작 미숙으로 인한 오인 신고',
    },
  },
  {
    id: 'AS-24007',
    siteName: 'A현장',
    dong: '101',
    ho: '905',
    trade: '설비',
    subTrade: '급수',
    defectType: {
      level1: '설비',
      level2: '급수',
      level3: '욕실',
      level4: '수압약함',
    },
    status: 'RECEIVED',
    priority: 'MEDIUM',
    partner: '대성설비',
    requester: '입주자-윤지호',
    requestedAt: '2025-10-05',
    dueDate: '2025-10-10',
    photos: {
      far: ['/images/as/far7.jpg'],
      near: ['/images/as/near7.jpg'],
    },
    attachments: [],
    description: '욕실 샤워기 수압이 약함',
    comments: 1,
    histories: [
      {
        id: 'HIST_013',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-10-05T11:00:00',
      },
    ],
    approval: {
      isApproved: false,
    },
  },
  {
    id: 'AS-24008',
    siteName: 'B현장',
    dong: '106',
    ho: '1801',
    trade: '마감',
    subTrade: '바닥재',
    defectType: {
      level1: '마감',
      level2: '바닥재',
      level3: '안방',
      level4: '긁힘',
    },
    status: 'ASSIGNED',
    priority: 'LOW',
    partner: '명품마감',
    assignee: '정기사',
    requester: '입주자-신동혁',
    requestedAt: '2025-10-06',
    dueDate: '2025-10-12',
    photos: {
      far: ['/images/as/far8.jpg'],
      near: ['/images/as/near8.jpg'],
    },
    attachments: [],
    description: '안방 바닥재에 긁힌 자국 발견',
    comments: 2,
    histories: [
      {
        id: 'HIST_014',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-10-06T13:00:00',
      },
      {
        id: 'HIST_015',
        type: 'ASSIGNMENT',
        title: '담당자 배정',
        description: '정기사님에게 배정되었습니다.',
        createdBy: '관리자-박현장',
        createdAt: '2025-10-06T14:00:00',
      },
    ],
    approval: {
      isApproved: false,
    },
  },
  {
    id: 'AS-24009',
    siteName: 'C현장',
    dong: '202',
    ho: '1205',
    trade: '창호',
    subTrade: '발코니',
    defectType: {
      level1: '창호',
      level2: '발코니',
      level3: '문틀',
      level4: '변형',
    },
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    partner: '삼성창호',
    assignee: '박기사',
    requester: '입주자-조은비',
    requestedAt: '2025-10-07',
    dueDate: '2025-10-11',
    photos: {
      far: ['/images/as/far9.jpg'],
      near: ['/images/as/near9.jpg'],
    },
    attachments: [
      {
        id: 'ATT_003',
        fileName: '발코니문_측정.xlsx',
        fileSize: 524288,
        fileUrl: '/files/as/measurement.xlsx',
        uploadedAt: '2025-10-07T10:00:00',
      },
    ],
    description: '발코니 문틀이 휘어진 것 같음',
    comments: 4,
    histories: [
      {
        id: 'HIST_016',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-10-07T10:00:00',
      },
      {
        id: 'HIST_017',
        type: 'STATUS_CHANGE',
        title: '처리 시작',
        description: '현장 확인 중',
        createdBy: '박기사',
        createdAt: '2025-10-08T09:00:00',
        oldValue: 'ASSIGNED',
        newValue: 'IN_PROGRESS',
      },
    ],
    approval: {
      isApproved: false,
    },
  },
  {
    id: 'AS-24010',
    siteName: 'A현장',
    dong: '103',
    ho: '702',
    trade: '전기',
    subTrade: '조명',
    defectType: {
      level1: '전기',
      level2: '조명',
      level3: '주방',
      level4: '깜박임',
    },
    status: 'RECEIVED',
    priority: 'MEDIUM',
    partner: '한빛전기',
    requester: '입주자-한지우',
    requestedAt: '2025-10-08',
    dueDate: '2025-10-13',
    photos: {
      far: ['/images/as/far10.jpg'],
      near: [],
    },
    attachments: [],
    description: '주방 조명이 간헐적으로 깜박임',
    comments: 0,
    histories: [
      {
        id: 'HIST_018',
        type: 'STATUS_CHANGE',
        title: '접수 완료',
        description: '접수가 완료되었습니다.',
        createdBy: '시스템',
        createdAt: '2025-10-08T15:00:00',
      },
    ],
    approval: {
      isApproved: false,
    },
  },
];
